import type { Metadata } from "next";

import { ThemeProviderWrapper } from "@/components/utils/theme/themeContextProvider";
import { ToastContainer } from "react-toastify";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProviderWrapper>
        <body>
          <ToastContainer
            position="bottom-right"
            autoClose={2500}
            hideProgressBar
            newestOnTop
            closeOnClick
          />
          <Header />

          {children}
          <footer>
            <Footer />
          </footer>
        </body>
      </ThemeProviderWrapper>
    </html>
  );
}
